### ISSUE TITLE
基于YOLOv5的 yaml 格式需修改

### ISSUE THREAD

**Issue by DeemoZen** [daimaohui/cvmart_yolov5#1]
套用fire.yaml跑代码会出现错误，在yolov5的general的513行：
 for k in 'train', 'val', 'names':
        assert k in data, emojis(f"data.yaml '{k}:' field missing ❌")
name被定义为了names，需要修改一下yaml

**Comment by daimaohui** [comment]
新版本的yolov5需要使用names,旧版本不需要，目前这个bug已经修复
